
services:
  xiidea.easy_audit.doctrine_subscriber:
          class: Xiidea\EasyAuditBundle\Subscriber\DoctrineSubscriber
          arguments: ['%xiidea.easy_audit.doctrine_objects%']
          calls:
              - [ setDispatcher,[ '@event_dispatcher' ] ]
              - [ setAnnotationReader,[ '@annotation_reader' ] ]
          tags:
              - { name: doctrine.event_listener, event: preRemove, method: preRemove }
              - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
              - { name: doctrine.event_listener, event: postRemove, method: postRemove }
              - { name: doctrine.event_listener, event: postPersist, method: postPersist }
              - { name: doctrine_mongodb.odm.event_listener }
